# Generated by Django 2.2.2 on 2019-06-21 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_incidentextension'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='squad',
            field=models.CharField(blank=True, choices=[('CO', 'Content-owner'), ('PB', 'Publisher'), ('PM', 'Player-monetization')], max_length=50, null=True),
        ),
    ]
