# Generated by Django 2.2.2 on 2019-06-27 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_incidentextension'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='severity',
        ),
        migrations.AddField(
            model_name='incident',
            name='squad',
            field=models.CharField(blank=True, choices=[('CONTENT SQUAD', '@content-squad'), ('PUBLISHER SQUAD', '@publisher-squad'), ('PLAYER & MONETIZATION', '@player-monetz-squad'), ('SRE SQUAD', '@sre'), ('DATA SQUAD', '@data-squad')], max_length=50, null=True),
        ),
    ]
