# Generated by Django 2.2.2 on 2019-06-25 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_incident_squad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='severity',
            field=models.CharField(blank=True, choices=[('CRIT', 'critical'), ('MAJOR', 'major'), ('MINOR', 'minor'), ('TRIVIAL', 'trivial')], max_length=10, null=True),
        ),
    ]
