# Generated by Django 2.2.2 on 2019-06-25 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190625_0820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='severity',
        ),
    ]
