# Generated by Django 2.2.2 on 2019-07-03 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_use_ExternalUser'),
        ('core', '0004_auto_20190627_0907'),
    ]

    operations = [
    ]
